name: unicorncalc
description: A calculator for Unicorns!
publish_to: 'none'
version: 1.1.0+2
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  termstyle: ^1.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: ProductSansBold
      fonts:
        - asset: assets/fonts/ProductSansBold.ttf
